### ISSUE TITLE
Build failed - can't connect to repository nexus.oit.umn.edu/content/groups/public

### ISSUE THREAD

**Issue by iversond** [UMN-PeopleSoft/IBMonitorService#4]
I'm building the project and it's failing when trying to connect to a UMN Maven repository. That repo isn't available to the outside world :)

**Comment by Dispader** [comment]
Hey, @carl0426 — looks like we've run into this problem already.  I think that Pull #3 should address this, though.

**Comment by carl0426** [comment]
I've merged Pull #3.  @iversond can you please try to build again?  Keep me posted on how it goes.

**Comment by iversond** [comment]
Build works great with Pull #3.
