### ISSUE TITLE
onCallFile Format

### ISSUE THREAD

**Issue by iversond** [UMN-PeopleSoft/IBMonitorService#6]
Can you give an sample of the oncall file? I'm unclear what data should be in `notification` for the format `name:notification`.

**Comment by carl0426** [comment]
A file would look something like this:
```
#Team oncall file for IB Monitor
#
# format ID:pager or email
# example Dick:5556090955@my2way.com
##MaxPowerEmail:max.power@someemail.com
BoHunterEmail:bo.hunter@someemail.com
MaxPowerCell:5556667788@vtext.com
##BoHunterCell:5551112233@tmomail.net
```
If "On Call" is notified, Bo Hunter would get an email and Max Power would get a page.

**Comment by carl0426** [comment]
Circling back on this issue and closing as no followup question/issue posted.
